name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - "*.*.x"
      - "master"

jobs:
#  phpunit:
#    name: "PHPUnit tests"
#
#    runs-on: ${{ matrix.operating-system }}
#
#    strategy:
#      matrix:
#        dependencies:
#          - "lowest"
#          - "highest"
#          - "locked"
#        php-version:
#          - "8.1"
#          - "8.2"
#        operating-system:
#          - "ubuntu-latest"
#          - "windows-latest"
#
#    steps:
#      - name: "Checkout"
#        uses: "actions/checkout@v3"
#
#      - name: "Install PHP"
#        uses: "shivammathur/setup-php@2.30.0"
#        with:
#          coverage: "none"
#          php-version: "${{ matrix.php-version }}"
#          ini-values: memory_limit=-1
#
#      - name: "Install dependencies"
#        uses: "ramsey/composer-install@2.2.0"
#        with:
#          dependency-versions: "${{ matrix.dependencies }}"
#
#      - name: "Run tests"
#        run: "vendor/bin/phpunit"

  static-analysis-phpstan:
    name: "Static Analysis by PHPStan"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"
          - "8.2"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.30.0"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Install dependencies"
        uses: "ramsey/composer-install@3.0.0"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "PHPStan"
        run: "vendor/bin/phpstan analyse --memory-limit=-1"

  lint:
    name: "Lint"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.30.0"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Install dependencies"
        uses: "ramsey/composer-install@3.0.0"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "Lint & validate composer.json"
        run: "composer validate && composer normalize"

      - name: "Check coding style"
        run: "vendor/bin/php-cs-fixer fix"

      - name: "Check architectural rules"
        run: "vendor/bin/phparkitect check"
