name: Run e2e test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "*.*.x"
      - "master"

jobs:

  run:
    name: "Run e2e test"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "highest"
          - "lowest"
          - "locked"
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.1.1"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.30.0"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Install dependencies"
        uses: "ramsey/composer-install@3.0.0"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "Init COMPOSER_HOME"
        uses: "ramsey/composer-install@3.0.0"
        with:
          working-directory: "tests/fixtures/composer_home"
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "Install e2e dependencies"
        uses: "ramsey/composer-install@3.0.0"
        with:
          working-directory: "tests/fixtures/e2e"

      - name: Test `composer audit` output
        # See https://github.com/symfony/symfony/issues/53460 why --no-ansi was added.
        run: tests/fixtures/e2e/test.php "$(DDQG_COMPOSER_AUDIT_TEST_ENV=1 COMPOSER_HOME=$PWD/tests/fixtures/composer_home ./vendor/bin/composer --no-ansi -d tests/fixtures/e2e audit --format=json)"
